<?php
/**
 * ShopApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BatteryIncluded API Documentation Copy
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Elio\ElioBatteryIncludedApiClient\Api;

use Elio\ElioDataDiscovery\Api\Configuration\Request\ConfigurationRequest;
use Elio\ElioDataDiscovery\Api\Recommendations\Request\RecommendationRequest;
use Elio\ElioDataDiscovery\Api\Search\Request\SearchRequest;
use Elio\ElioDataDiscovery\Api\Search\Request\SuggestRequest;
use Elio\ElioDataDiscovery\Core\Util\StringUtil;
use Elio\ElioDataDiscovery\Swagger\ClientApiException;
use Elio\ElioDataDiscovery\Swagger\ClientConfiguration;
use Elio\ElioDataDiscovery\Swagger\ClientHeaderSelector;
use Elio\ElioDataDiscovery\Swagger\ClientObjectSerializer;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Promise\PromiseInterface;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Query;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use InvalidArgumentException;
use RuntimeException;
use stdClass;

/**
 * ShopApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SearchApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var ClientConfiguration
     */
    protected ClientConfiguration $config;

    /**
     * @var ClientHeaderSelector
     */
    protected ClientHeaderSelector $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration $config
     * @param HeaderSelector $selector
     */
    public function __construct(
        ClientInterface $client = null,
        ClientConfiguration $config = null,
        ClientHeaderSelector $selector = null
    )
    {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new ClientConfiguration();
        $this->headerSelector = $selector ?: new ClientHeaderSelector();
    }

    /**
     * @return ClientConfiguration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation filter
     *
     * Filter
     *
     * @param SearchRequest $searchRequest searchRequest (optional)
     * @param array $variables variables (optional)
     * @param array $filters filters (optional)
     *
     * @throws ClientApiException on non-2xx response
     * @throws InvalidArgumentException
     */
    public function filter($searchRequest, $variables = null, $filters = null)
    {
        list($response) = $this->filterWithHttpInfo($searchRequest, $variables, $filters);
        return $response;
    }

    /**
     * Operation filterWithHttpInfo
     *
     * Filter
     *
     * @param SearchRequest $searchRequest (optional)
     * @param array $variables variables (optional)
     * @param array $filters filters (optional)
     *
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws InvalidArgumentException
     * @throws ClientApiException on non-2xx response
     */
    public function filterWithHttpInfo($searchRequest, $variables = null, $filters = null)
    {
        $returnType = '\Elio\ElioBatteryIncludedApiClient\Model\Result';
        $request = $this->filterRequest($searchRequest, $variables, $filters);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ClientApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ClientApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ClientObjectSerializer::deserialize($content, $returnType, []),
                $statusCode,
                $response->getHeaders()
            ];

        } catch (ClientApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation filterAsync
     *
     * Filter
     *
     * @param SearchRequest $searchRequest (optional)
     * @param array $variables variables (optional)
     * @param array $filters filters (optional)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function filterAsync($searchRequest, $variables = null, $filters = null)
    {
        return $this->filterAsyncWithHttpInfo($searchRequest, $variables, $filters)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation filterAsyncWithHttpInfo
     *
     * Filter
     *
     * @param SearchRequest $searchRequest (optional)
     * @param array $variables variables (optional)
     * @param array $filters $filters (optional)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function filterAsyncWithHttpInfo($searchRequest, $variables = null, $filters = null)
    {
        $returnType = '';
        $request = $this->filterRequest($searchRequest, $variables, $filters);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ClientApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'filter'
     *
     * @param SearchRequest $searchRequest (optional)
     * @param array $variables variables (optional)
     * @param array $filters filters (optional)
     *
     * @return Request
     * @throws InvalidArgumentException
     */
    protected function filterRequest($searchRequest, $variables = null, $filters = null)
    {
        $resourcePath = sprintf('/api/v1/collections/%s/documents/browse', $this->config->getCollection());
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $q = $searchRequest->getQuery();
        $queryParams['q'] = ClientObjectSerializer::toQueryValue($q, null);

        if (is_array($filters)) {
            foreach ($filters as $key => $filter) {
                if (is_array($filter)) {
                    foreach ($filter as $item) {
                        $item = StringUtil::decodeStringFromUnescapedUnicode($item);
                        $key = StringUtil::decodeStringFromUnescapedUnicode($key);
                        $queryParams[$key][] = ClientObjectSerializer::toQueryValue($item, null);
                    }
                } else {
                    $queryParams[$key][] = ClientObjectSerializer::toQueryValue($filter, null);
                }

            }
        } else {
            $queryParams['filters'] = ClientObjectSerializer::toQueryValue($filters, null);
        }

        if (is_array($variables)) {
            foreach ($variables as $key => $variable) {
                $queryParams[$key] = ClientObjectSerializer::toQueryValue($variable, null);
            }
        }

        // header params
        if ($this->config->getApiKey('serverApiKey') !== null) {
            $headerParams['X-BI-API-KEY'] = $this->config->getApiKey('serverApiKey');
            $headerParams['X-BI-REQUEST-ID'] = $searchRequest->getRequestId();
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = Query::build($queryParams);

        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation suggest
     *
     * Suggest
     *
     * @param SuggestRequest $suggestRequest suggestRequest (optional)
     * @param array $variables variables (optional)
     * @param array $filters filters (optional)
     *
     * @throws ClientApiException on non-2xx response
     * @throws InvalidArgumentException
     */
    public function suggest($suggestRequest, $variables = null, $filters = null)
    {
        list($response) = $this->suggestWithHttpInfo($suggestRequest, $variables, $filters);
        return $response;
    }

    /**
     * Operation suggestWithHttpInfo
     *
     * Suggest
     *
     * @param SuggestRequest $suggestRequest (optional)
     * @param array $variables variables (optional)
     * @param array $filters filters (optional)
     *
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws InvalidArgumentException
     * @throws ApiException on non-2xx response
     */
    public function suggestWithHttpInfo($suggestRequest, $variables = null, $filters = null)
    {
        $returnType = '\Elio\ElioBatteryIncludedApiClient\Model\SuggestionResult[]';
        $request = $this->suggestRequest($suggestRequest, $variables, $filters);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ClientApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ClientApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ClientObjectSerializer::deserialize($content, $returnType, []),
                $statusCode,
                $response->getHeaders()
            ];
        } catch (ClientApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation suggestAsync
     *
     * Suggest
     *
     * @param SuggestRequest $suggestRequest (optional)
     * @param array $variables variables (optional)
     * @param array $filters filters (optional)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function suggestAsync($suggestRequest, $variables = null, $filters = null)
    {
        return $this->suggestAsyncWithHttpInfo($suggestRequest, $variables, $filters)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation suggestAsyncWithHttpInfo
     *
     * Suggest
     *
     * @param SuggestRequest $suggestRequest (optional)
     * @param array $variables variables (optional)
     * @param array $filters filters (optional)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function suggestAsyncWithHttpInfo($suggestRequest, $variables = null, $filters = null)
    {
        $returnType = '';
        $request = $this->suggestRequest($suggestRequest, $variables, $filters);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ClientApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'suggest'
     *
     * @param SuggestRequest $suggestRequest (optional)
     * @param array $variables variables (optional)
     * @param array $filters filters (optional)
     *
     * @return Request
     * @throws InvalidArgumentException
     */
    protected function suggestRequest($suggestRequest, $variables = null, $filters = null)
    {
        $resourcePath = sprintf('/api/v1/collections/%s/documents/suggest', $this->config->getCollection());
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $q = $suggestRequest->getQuery();
        $queryParams['q'] = ClientObjectSerializer::toQueryValue($q, null);

        if (is_array($filters)) {
            foreach ($filters as $key => $filter) {
                if (is_array($filter)) {
                    foreach ($filter as $item) {
                        $item = StringUtil::decodeStringFromUnescapedUnicode($item);
                        $key = StringUtil::decodeStringFromUnescapedUnicode($key);
                        $queryParams[$key][] = ClientObjectSerializer::toQueryValue($item, null);
                    }
                } else {
                    $queryParams[$key][] = ClientObjectSerializer::toQueryValue($filter, null);
                }

            }
        } else {
            $queryParams['filters'] = ClientObjectSerializer::toQueryValue($filters, null);
        }

        if (is_array($variables)) {
            foreach ($variables as $key => $variable) {
                $queryParams[$key] = ClientObjectSerializer::toQueryValue($variable, null);
            }
        }

        // header params
        if ($this->config->getApiKey('serverApiKey') !== null) {
            $headerParams['X-BI-API-KEY'] = $this->config->getApiKey('serverApiKey');
            //$headerParams['X-BI-REQUEST-ID'] = $suggestRequest->getRequestId();
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation recommend
     *
     * Recommend
     *
     * @param RecommendationRequest $recommendationRequest recommendationRequest (optional)
     * @param string $locale locale (optional)
     *
     * @throws ClientApiException on non-2xx response
     * @throws InvalidArgumentException
     */
    public function recommend($recommendationRequest, $locale)
    {
        list($response) = $this->recommendWithHttpInfo($recommendationRequest, $locale);
        return $response;
    }

    /**
     * Operation recommendWithHttpInfo
     *
     * Recommend
     *
     * @param RecommendationRequest $recommendationRequest (optional)
     * @param string $locale (optional)
     *
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws InvalidArgumentException
     * @throws ApiException on non-2xx response
     */
    public function recommendWithHttpInfo($recommendationRequest, string $locale)
    {
        $returnType = '\Elio\ElioBatteryIncludedApiClient\Model\RecommendationResult[]';
        $request = $this->recommendRequest($recommendationRequest, $locale);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ClientApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ClientApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ClientObjectSerializer::deserialize($content, $returnType, []),
                $statusCode,
                $response->getHeaders()
            ];
        } catch (ClientApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation recommendAsync
     *
     * Recommend
     *
     * @param RecommendationRequest $recommendationRequest (optional)
     * @param string $locale (optional)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function recommendAsync($recommendationRequest, $locale)
    {
        return $this->recommendAsyncWithHttpInfo($recommendationRequest, $locale)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation recommendAsyncWithHttpInfo
     *
     * Recommend
     *
     * @param RecommendationRequest $recommendationRequest (optional)
     * @param string $locale (optional)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function recommendAsyncWithHttpInfo($recommendationRequest, $locale)
    {
        $returnType = '';
        $request = $this->recommendRequest($recommendationRequest, $locale);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ClientApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'recommend'
     *
     * @param RecommendationRequest $recommendationRequest (optional)
     * @param string $locale (optional)
     *
     * @return Request
     * @throws InvalidArgumentException
     */
    protected function recommendRequest($recommendationRequest, $locale)
    {
        $resourcePath = sprintf('/api/v1/collections/%s/documents/recommendations', $this->config->getCollection());
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $id = $recommendationRequest->getProductNumber();
        $queryParams['id'] = ClientObjectSerializer::toQueryValue($id, null);

        // header params
        if ($this->config->getApiKey('serverApiKey') !== null) {
            $headerParams['X-BI-API-KEY'] = $this->config->getApiKey('serverApiKey');
            //$headerParams['X-BI-REQUEST-ID'] = $recommendationRequest->getRequestId();
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation configuration
     *
     * Configuration
     *
     * @param ConfigurationRequest $configurationRequest configurationRequest (optional)
     *
     * @throws ClientApiException on non-2xx response
     * @throws InvalidArgumentException
     */
    public function configuration($configurationRequest)
    {
        list($response) = $this->configurationWithHttpInfo($configurationRequest);
        return $response;
    }

    /**
     * Operation configurationWithHttpInfo
     *
     * Configuration
     *
     * @param ConfigurationRequest $configurationRequest (optional)
     *
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws InvalidArgumentException
     * @throws ApiException on non-2xx response
     */
    public function configurationWithHttpInfo($configurationRequest)
    {
        $request = $this->configurationRequest($configurationRequest);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ClientApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ClientApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            $content = $responseBody->getContents();
            $content = json_decode($content);

            return [
                $content,
                $statusCode,
                $response->getHeaders()
            ];
        } catch (ClientApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation configurationAsync
     *
     * Configuration
     *
     * @param ConfigurationRequest $configurationRequest (optional)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function configurationAsync($configurationRequest)
    {
        return $this->configurationAsyncWithHttpInfo($configurationRequest)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation configurationAsyncWithHttpInfo
     *
     * Configuration
     *
     * @param ConfigurationRequest $configurationRequest (optional)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function configurationAsyncWithHttpInfo($configurationRequest)
    {
        $returnType = '';
        $request = $this->configurationRequest($configurationRequest);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ClientApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'configuration'
     *
     * @param ConfigurationRequest $configurationRequest (optional)
     *
     * @return Request
     * @throws InvalidArgumentException
     */
    protected function configurationRequest($configurationRequest)
    {
        $resourcePath = sprintf('/api/v1/collections/%s/documents/presets', $this->config->getCollection());
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($this->config->getApiKey('serverApiKey') !== null) {
            $headerParams['X-BI-API-KEY'] = $this->config->getApiKey('serverApiKey');
            //$headerParams['X-BI-REQUEST-ID'] = $configurationRequest->getRequestId();
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @return array of http client options
     * @throws RuntimeException on file opening failure
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
